name: build docker image

on: push

env:
  DOCKER_REPO: ghcr.io/jonohill/docker-s6-package

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read s6 version
        id: read_version
        run: |
          raw_version="$(cat version.txt | grep S6_VERSION | sed 's/S6_VERSION=//g')"
          version="$(echo "$raw_version" | sed 's/v//g')"
          echo "::set-output name=raw_version::$version"
          echo "::set-output name=version::$version"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.multi
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v7
            linux/arm64
            linux/riscv64
            linux/s390x
          build-args: |
            S6_VERSION=${{ steps.read_version.outputs.raw_version }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ env.DOCKER_REPO }}:latest
            ${{ env.DOCKER_REPO }}:${{ steps.read_version.outputs.version }}
